#src_v2/observability/telemetry.py
import json
import os
from datetime import datetime
from typing import List, Tuple, Optional
from langchain_core.documents import Document
from opentelemetry import trace, metrics



# This tracer will be imported by your LangGraph nodes to create manual spans.
tracer = trace.get_tracer("nichedocbot.tracer")

# This meter emits custom application metrics for Splunk dashboards.
meter = metrics.get_meter("nichedocbot.metrics")

rag_retrieval_duration_ms = meter.create_histogram(
    name="rag.retrieval.duration_ms",
    unit="ms",
    description="Duration of vector retrieval during RAG answer generation.",
)

rag_retrieval_chunk_count = meter.create_histogram(
    name="rag.retrieval.chunk_count",
    unit="{chunks}",
    description="Number of chunks returned by vector retrieval.",
)

rag_retrieval_top_score = meter.create_histogram(
    name="rag.retrieval.top_score",
    unit="1",
    description="Top retrieval distance score returned by vector search.",
)

llm_duration_ms = meter.create_histogram(
    name="llm.duration_ms",
    unit="ms",
    description="Duration of LLM generation call.",
)

llm_prompt_tokens = meter.create_histogram(
    name="llm.prompt_tokens",
    unit="{tokens}",
    description="Prompt/input tokens used by the LLM request.",
)

llm_completion_tokens = meter.create_histogram(
    name="llm.completion_tokens",
    unit="{tokens}",
    description="Completion/output tokens generated by the LLM response.",
)

llm_total_tokens = meter.create_histogram(
    name="llm.total_tokens",
    unit="{tokens}",
    description="Total tokens used by the LLM request and response.",
)


def _clean_metric_attributes(attributes: dict) -> dict:
    """
    Remove None values before sending attributes to OpenTelemetry metrics.
    """
    return {key: value for key, value in attributes.items() if value is not None}


def record_rag_retrieval_metrics(
    *,
    repo_id: str,
    chunk_count: int,
    duration_ms: float,
    top_score: Optional[float] = None,
    workflow_type: str = "rag_answer",
) -> None:
    """
    Emit RAG retrieval metrics for dashboard charting.
    """
    attrs = _clean_metric_attributes({
        "workflow.type": workflow_type,
        "rag.repo": repo_id,
    })

    rag_retrieval_duration_ms.record(float(duration_ms), attrs)
    rag_retrieval_chunk_count.record(int(chunk_count), attrs)

    if top_score is not None:
        rag_retrieval_top_score.record(float(top_score), attrs)


def record_llm_metrics(
    *,
    model: str,
    duration_ms: float,
    prompt_tokens: Optional[int] = None,
    completion_tokens: Optional[int] = None,
    total_tokens: Optional[int] = None,
    is_multimodal: Optional[bool] = None,
    repo_id: Optional[str] = None,
    workflow_type: str = "rag_answer",
) -> None:
    """
    Emit LLM latency and token metrics for dashboard charting.
    """
    attrs = _clean_metric_attributes({
        "workflow.type": workflow_type,
        "llm.model": model,
        "llm.is_multimodal": is_multimodal,
        "rag.repo": repo_id,
    })

    llm_duration_ms.record(float(duration_ms), attrs)

    if prompt_tokens is not None:
        llm_prompt_tokens.record(int(prompt_tokens), attrs)
    if completion_tokens is not None:
        llm_completion_tokens.record(int(completion_tokens), attrs)
    if total_tokens is not None:
        llm_total_tokens.record(int(total_tokens), attrs)


def add_retrieved_document_events(
    span,
    docs_with_scores: List[Tuple[Document, float]],
) -> None:
    """
    Add one OpenTelemetry span event per retrieved document.

    This provides per-document retrieval visibility without storing full
    document content in traces.
    """
    if not span or not docs_with_scores:
        return

    for index, (doc, score) in enumerate(docs_with_scores):
        metadata = doc.metadata or {}
        content = doc.page_content or ""

        span.add_event(
            "retrieved_document",
            {
                "rag.document_index": index,
                "rag.source": metadata.get("source", "unknown"),
                "rag.element_type": metadata.get("element_type", "unknown"),
                "rag.distance_score": float(score),
                "rag.content_preview_length": len(content[:250]),
            },
        )

def log_rag_retrieval(query: str, docs_with_scores: List[Tuple[Document, float]], llm_response: str, repo_id: str):
    """
    Logs RAG retrieval metrics to a local JSONL file for analysis.
    Every line is a valid JSON object, making it easy to parse in Pandas or Jupyter.
    """
    data_dir = os.getenv("DATA_DIR", "data")
    log_dir = os.path.join(data_dir, "telemetry")
    os.makedirs(log_dir, exist_ok=True)
    log_file = os.path.join(log_dir, "rag_logs.jsonl")

    # Format the retrieved chunks for the log
    retrieved_data = []
    for doc, score in docs_with_scores:
        retrieved_data.append({
            "source": doc.metadata.get("source", "unknown"),
            "element_type": doc.metadata.get("element_type", "unknown"),
            "distance_score": float(score), # Chroma uses distance (lower is closer/better)
            "content_preview": doc.page_content[:250] + "..." # Truncated to keep logs manageable
        })

    # Build the final telemetry payload
    log_entry = {
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "repo_id": repo_id,
        "user_query": query,
        "retrieved_chunks": retrieved_data,
        "llm_response": llm_response
    }

    # Append to the JSONL file (creates the file if it doesn't exist)
    with open(log_file, "a", encoding="utf-8") as f:
        f.write(json.dumps(log_entry) + "\n")