apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-routing-config
  namespace: default
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://splunk-otel-splunk-otel-collector-agent.splunk-otel.svc.cluster.local:4317"
